name: Publish
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: eclipse-temurin:17-jdk
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
        
      - name: Bump Version
        run: ./bump_version.sh;
        env:
          BASE_VERSION: ${{ vars.BASE_VERSION }}
          PATCH_VERSION: ${{ vars.PATCH_VERSION }}

      - name: Publish to Maven
        run: ./gradlew build :felt-spindle:publish -x test --stacktrace;
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_PUBLISH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PUBLISH_TOKEN }}